### ISSUE TITLE
byte array em C++

### ISSUE THREAD

**Issue by gmcarelli** [gmcarelli/medical-database-analysis-cpp#2]
o tipo "byte" não é um tipo primitivo em C.  A primeira solução encontrada é o uso de um array de char.
Será viável na hora de recuperar os bytes da imagem gravados no banco? Possível problema de conversão?

**Comment by lucasvenez** [comment]
@gmcarelli,

Você pode utilizar `unsigned char abc[3]` para definir o equivalente a `new byte[3]` em Java. Além disso, você pode definir o tipo `byte`da seguinte forma: `using byte = unsigned char`.

**Comment by gmcarelli** [comment]
Já criei duas classes MyImage, uma implementando como char[] e outra utilizando a bilbioteca do C++ <cstdint> e o tipo inteiro de 8 bits, int8_t.
